### PR TITLE
Discussion of changes

### PR DESCRIPTION
**Pull request by dmytrokohut**

### CODE REVIEW

**Review by Milkho — CHANGES_REQUESTED** [review]
1. It'll be better to have all dao classes and interfaces in one package. 
2. It's a bad idea to use "I" prefix for naming intefaces in Java. 
3. Where's the data layer? It's better to create (commit)  data layer before dao and service layers.
4. Fix grammatical mistakes in the documentation.
5. Add transaction support. The JdbcTemplate doesn't provide transaction support out-of-the-box. At least annotate dao methods with @Transactional.

**Comment by dmytrokohut** [comment]
Hi, @Milkho 
Take my appreciation for Your comments and see my answers below:

1. There are different ways of grouping interfaces and classes, for my opinion, the best way is splitting interfaces and classes into separate packages. The advantage of this way is clear separating interfaces and classes.
2. The same situation as the previous question. I prefer using the similar names for interfaces and classes where the prefix "I" means that it is an interface. The advantage is more comfortable using of names of interfaces and classes.
3. As I understand You are talking about a layer that realizes business logic of the application. If that's what are You said about so You are absolutely right, the application should have an additional layer for business logic if that exists. But as written in the description this is a training project and its purpose is practice in using gRPC framework, therefore this application doesn't solve business tasks and as a consequence, there is not business layer.
4. It would be great if You are showed my grammar mistakes on existing examples and explain how to write better.
5. @Transaction annotation means that even only one operation will be executing as transaction this means that it will be used more resources. This is very useful annotation if you prefer security rather than performance. In the case of my application, it is not necessary to use this annotation, so this annotation can both used and not used.

Thanks, finr1r

**Comment by Milkho** [comment]
Hi, @finr1r.  I'm glad to see your feedback. Please, let me explain in more detail, what my comments mean. 

1. There are different ways of grouping interfaces and classses, indeed. But the way I described is de facto universally accepted - it is used by Java developers themselves. Anyway, I don't insist on this,  just recommend.
2. The same story. Prefix "I" is the .NET name convention, not Java.  If you write the code only for yourself, then OK. If someone will have to work with your code, it can be confusing.
3. Actually, I was talking about "entity" package. You used classes from that package but I can't find where  is it.
4. The most common mistake is the wrong writing of verb endings. In the  Present Simple verb form 3rd person singular we add “s”, “es” or “ies” at the end of the verb. 
5. I'm not sure I understand what do you mean by "security" in this case.  And I'm sure that using of transaction won't greatly affect the performance but will guarantee acid. Even if it is a simple app.

I hope, my comments were usefull for you.

**Comment by dmytrokohut** [comment]
Hi, @Milkho 
I'm glad to see Your response
About questions, see my answers below:

1. and 2. questions - I offer to You to discuss this issues with our team in our group meeting, so after discussion, we will have a single standard of the naming of interfaces and splitting interfaces and classes into packages.
3. The entity package could be filled by classes generated by Protocol Buffer compiler. I was generating this classes when I was working with them, after application is ready them could be removed as Gradle compiler generate them each time when the program is running.
4. Thank You for Your advices. I will take Your note for further documentation.
5. I suppose You are right and I will add this annotation tomorrow (maybe someone from our team will add commentaries to this pull request).

Thanks, finr1r

**Pull request closed without merging**
